### ISSUE TITLE
what is api keys

### ISSUE THREAD

**Issue by hirdesh16** [hetmann/node-sms-server#1]

**Comment by hirdesh16** [comment]
how to set api keys when using gsm modem and Phone numver invalid error is shown

**Comment by hetmann** [comment]
@hirdesh16 
1. edit **keys** in the [config file](https://github.com/hetmann/node-sms-server/blob/master/lib/config.js#L4)
2. edit frontend api_key in the [sms.js file](https://github.com/hetmann/node-sms-server/blob/master/views/sms.jade#L5)

Example: the `keys` from config.js corelate with the frontend `api_key` is **demo** and `api_secret` is **Demo_Secret_Key**

**Comment by hirdesh16** [comment]
Dear thanks a lot ...i finally found it.
